### ISSUE TITLE
Bows are unable to fire in survival

### ISSUE THREAD

**Issue by PixitOwO** [Team-Hibiscus/NaturesDelight#9]
Bows are unable to be drawn back in survival, but work fine in creative. I am using the newest release and just using required mods, the issue still persists.

**Comment by KMaxK9** [comment]
I encounter the same problem. I think it is due to an inventory reading error, that doesn't let the game find arrows in the inventory even when you have projectiles in it.

**Comment by kands-code** [comment]
Oh, I finally found this issue. At first, I thought it was caused by Better Combat, because in my understanding, the only mod I am using that could potentially modify the right-click logic is Better Combat. However, after checking the author's notes and conducting a binary search, I found out that the issue was caused by the Nature's Delight mod. This is quite strange.

For a detailed description of this issue, please refer to this [Issue](https://github.com/ZsoltMolnarrr/BetterCombat/issues/447).

**Comment by Eko-byte** [comment]
Fixed !

**Comment by kands-code** [comment]
> Fixed !

Not really. At least the 1.20.1 version has not been fully fixed. I haven't seen any new updates regarding the 1.20.1 version on Modrith, and this issue still exists in 1.20.1.
